// packages/text-editor/react-components/src/placeholder/index.tsx
import { createPortal } from 'react-dom';
import { type ReactNode } from 'react';

import { useHTMLElement, useInjectorEffect } from '@text-editor/react-hooks';
import {
  placeholder,
  activeLinePlaceholder,
} from '@text-editor/extension-placeholder';

function Placeholder({ children }: { children?: ReactNode }): ReactNode {
  const element = useHTMLElement('span');

  useInjectorEffect(
    injector => injector.inject([placeholder(() => element)]),
    [],
  );

  return createPortal(children, element);
}

interface ActiveLinePlaceholderProps {
  children?: ReactNode;
}

function ActiveLinePlaceholder({
  children,
}: ActiveLinePlaceholderProps): ReactNode {
  const element = useHTMLElement('span');

  useInjectorEffect(
    injector => injector.inject([activeLinePlaceholder(() => element)]),
    [],
  );

  return createPortal(children, element);
}

export { Placeholder, ActiveLinePlaceholder };

// packages/text-editor/vue-components/src/placeholder.tsx
import { h, defineComponent, onBeforeMount, onUnmounted, Teleport } from 'vue'
import { placeholder } from '@text-editor/extension-placeholder'
import { useInjector } from '@text-editor/vue'

const Placeholder = defineComponent({
  setup(_props, { slots }) {
    const element = document.createElement('span')

    const injector = useInjector()

    let eject: (() => void) | null = null

    onBeforeMount(() => {
      eject = injector.inject([
        placeholder(() => element),
      ])
    })

    onUnmounted(() => {
      if (eject) {
        eject()
      }
    })

    return () => h(Teleport, { to: element }, [
      slots.default ? slots.default() : undefined,
    ])
  },
})

export {
  Placeholder,
}
