// packages/text-editor/vue-components/src/cursor-mirror.tsx
import { defineComponent, onBeforeMount, onMounted, onUnmounted, type PropType } from 'vue';
import { type BuiltinEditorAPI } from '@text-editor/vue';
import { elementAtPosition, positionElementLayer, SelectionSide } from '@text-editor/extensions';
import { autoUpdate } from '@floating-ui/dom';

import { useEditorRef, useInjector } from '@text-editor/vue';

const CursorMirror = defineComponent({
  props: {
    side: String as PropType<SelectionSide>,
    onChange: Function as PropType<() => void>,
    onVisibleChange: Function as PropType<(visible: boolean) => void>,
  },

  setup({ side, onChange, onVisibleChange }, { expose }) {
    const injector = useInjector()
    const editor = useEditorRef<BuiltinEditorAPI>()
    const dom = document.createElement('div')

    expose({ element: dom })

    let eject: (() => void) | null = null
    onBeforeMount(() => {
      eject = injector.inject([
        elementAtPosition.of({
          dom,
          pos: side!,
        }),
        positionElementLayer,
      ])
    })
    onUnmounted(() => {
      if (typeof eject === 'function') {
        eject()
      }
    })

    // watch for position change
    let disposeUpdateWatcher: (() => void) | null = null
    onMounted(() => {
      const floating = document.createElement('div');
      document.body.appendChild(floating);

      const dispose = autoUpdate(dom, floating, () => {
        if (typeof onChange === 'function') {
          onChange()
        }
      }, { animationFrame: true });

      disposeUpdateWatcher = () => {
        document.body.removeChild(floating);
        dispose();
      }
    })
    onUnmounted(() => {
      if (typeof disposeUpdateWatcher === 'function') {
        disposeUpdateWatcher()
        disposeUpdateWatcher = null
      }
    })

    // watch for visible change
    let disposeVisibleWatcher: (() => void) | null = null
    onMounted(() => {
      if (!editor) {
        return;
      }

      const view = editor.value!.$view

      const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
          if (typeof onVisibleChange === 'function') {
            onVisibleChange(entry.isIntersecting);
          }
        });
      }, {
        root: view.scrollDOM,
        threshold: 0,
      });

      observer.observe(dom);

      disposeVisibleWatcher = () => {
        observer.disconnect()
      }
    })
    onUnmounted(() => {
      if (typeof disposeVisibleWatcher === 'function') {
        disposeVisibleWatcher()
        disposeVisibleWatcher = null
      }
    })

    return {}
  },

  render() {
    return null
  },
})

export {
  CursorMirror,
  SelectionSide,
}

// packages/text-editor/react-components/src/cursor-mirror/index.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useLayoutEffect,
  useRef,
  useState,
} from 'react';

import { type BuiltinEditorAPI } from '@text-editor/react';
import { useEditor, useInjector } from '@text-editor/react';
import {
  elementAtPosition,
  positionElementLayer,
  SelectionSide,
} from '@text-editor/extensions';
import { autoUpdate } from '@floating-ui/dom';

interface Props {
  side: SelectionSide;
  onChange?: () => void;
  onVisibleChange?: (visible: boolean) => void;
}

const CursorMirror = forwardRef<HTMLDivElement, Props>(function CursorMirror(
  { side, onChange, onVisibleChange },
  ref,
) {
  const injector = useInjector();
  const editor = useEditor<BuiltinEditorAPI>();
  const [dom] = useState(() => document.createElement('div'));
  const domRef = useRef<HTMLDivElement>(dom);
  domRef.current = dom;
  const onChangeRef = useRef(onChange);
  onChangeRef.current = onChange;
  const onVisibleChangeRef = useRef(onVisibleChange);
  onVisibleChangeRef.current = onVisibleChange;

  useImperativeHandle(ref, () => domRef.current);

  useLayoutEffect(
    () =>
      injector.inject([
        elementAtPosition.of({
          dom: domRef.current,
          pos: side,
        }),
        positionElementLayer,
      ]),
    [injector, side],
  );

  // watch for position change
  useEffect(() => {
    const floating = document.createElement('div');
    document.body.appendChild(floating);

    const dispose = autoUpdate(
      domRef.current,
      floating,
      () => {
        if (typeof onChangeRef.current === 'function') {
          onChangeRef.current();
        }
      },
      { animationFrame: true },
    );

    return () => {
      document.body.removeChild(floating);
      dispose();
    };
  }, []);

  // watch for visible change
  useEffect(() => {
    if (!editor) {
      return;
    }

    const view = editor.$view;

    const observer = new IntersectionObserver(
      entries => {
        entries.forEach(entry => {
          if (typeof onVisibleChangeRef.current === 'function') {
            onVisibleChangeRef.current(entry.isIntersecting);
          }
        });
      },
      {
        root: view.scrollDOM,
        threshold: 0,
      },
    );

    observer.observe(domRef.current);

    return () => {
      observer.disconnect();
    };
  }, [editor]);

  return null;
});

export { CursorMirror, SelectionSide };
